POST http://localhost:3004/register
Content-Type: application/json

{
    "username":"sanni",
    "password":"9059",
    "gender":"Male",
    "fullname":"Shaik Sandani"
}
###
POST http://localhost:3004/login
Content-Type: application/json

{
    "username":"sanni",
    "password":"9059"
}

###
POST http://localhost:3004/todos 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzNkOGE5NDMzZDcyNGNlNjUzMWMxZWEiLCJ1c2VybmFtZSI6InNhbm5pIiwiZnVsbG5hbWUiOiJTaGFpayBTYW5kYW5pIiwiZ2VuZGVyIjoiTWFsZSIsImlhdCI6MTczMjE2MDYzOSwiZXhwIjoxNzMyMTY0MjM5fQ.gTfdwIyfzd4AxjjvBTOFCumjTQVEWoFW27WbR9uY9l4

{
    "todo": "Pack suitcase for business trip",
    "tag": "Travel",
    "priority": "medium"
}
###
PUT http://localhost:3004/todos/673eb137ef7fe8d1ccf08129
Content-Type: application/json

{
    "todo": "Pack suitcase for business trip",
    "tag": "Travel",
    "priority": "high",
    "status": "completed"
}

###
GET http://localhost:3004/todos?tag=Health&priority=high&status=pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzNkOGE5NDMzZDcyNGNlNjUzMWMxZWEiLCJ1c2VybmFtZSI6InNhbm5pIiwiZnVsbG5hbWUiOiJTaGFpayBTYW5kYW5pIiwiZ2VuZGVyIjoiTWFsZSIsImlhdCI6MTczMjE2NTMxOSwiZXhwIjoxNzMyMTY4OTE5fQ.HsR6Jn5KvJjeZXLLGemW-adZQvEG5K0TbxVrAm_y55I
