POST http://localhost:3004/feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODdhMzNhNTI1NTAyZWRhYjA3NDRhZTgiLCJ1c2VybmFtZSI6InNhbm5pIiwiZnVsbG5hbWUiOiJzYW5uaSIsImdlbmRlciI6Im1hbGUiLCJpYXQiOjE3NTQyNzIyNzMsImV4cCI6MTc1NDM1ODY3M30.pngS9aJChlXahgwiLdky7PPz6fLPavaNAMuobUtYzSg

{
    "type":"feedback",
    "message":"This App Really Feels Cool and UI was Great, Great App but needs huge Improvements"
}

###
DELETE  http://localhost:3004/feedback/689044082c4ed1f7429e0250
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODdhMzNhNTI1NTAyZWRhYjA3NDRhZTgiLCJ1c2VybmFtZSI6InNhbm5pIiwiZnVsbG5hbWUiOiJzYW5uaSIsImdlbmRlciI6Im1hbGUiLCJpYXQiOjE3NTQyNzIyNzMsImV4cCI6MTc1NDM1ODY3M30.pngS9aJChlXahgwiLdky7PPz6fLPavaNAMuobUtYzSg

###
GET http://localhost:3004/feedbacks?status=pending&type=feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODdhMzNhNTI1NTAyZWRhYjA3NDRhZTgiLCJ1c2VybmFtZSI6InNhbm5pIiwiZnVsbG5hbWUiOiJzYW5uaSIsImdlbmRlciI6Im1hbGUiLCJpYXQiOjE3NTQyNzIyNzMsImV4cCI6MTc1NDM1ODY3M30.pngS9aJChlXahgwiLdky7PPz6fLPavaNAMuobUtYzSg
